esphome:
  name: display-office
  platformio_options:
    build_type: debug
  includes:
    - "includes/shared.h"
    - "display-office.h"
  on_boot:
    - then:
        - component.update: epaper


packages:
  - !include includes/base.yaml
  - !include includes/esp32c3.yaml
  - !include includes/waveshare.yaml


external_components:
  - source:
      type: local
      path: external_components


font:
  - file: "gfonts://Material+Symbols+Outlined"
    id: icons256
    size: 256
    glyphs:
      - "\U0000e63e"
      - "\U0000f063"
  - file: "gfonts://Material+Symbols+Outlined"
    id: icons64
    size: 64
    glyphs:
      - "\U0000e6ca"
      - "\U0000eb8b"
      - "\U0000e81a"
      - "\U0000f036"
      - "\U0000e2bd"
      - "\U0000f172"
      - "\U0000f176"
      - "\U0000f61f"
      - "\U0000e2cd"
      - "\U0000f60b"
      - "\U0000ebdb"
      - "\U0000efd8"
      - "\U0000e818"
      - "\U0000f67f"


wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Display-Office Fallback Hotspot"
    password: "wwhbTrI9hT2A"

  on_connect:
    - component.update: epaper
    - component.update: events
    - component.update: weather_daily
    - component.update: weather_hourly
    - component.update: local_flights
  on_disconnect:
    - component.update: epaper


captive_portal:


time:
  - platform: homeassistant
    id: rtc
    timezone: Europe/London
    on_time:
      - seconds: 0
        then:
          - component.update: epaper
    on_time_sync:
      then:
        - component.update: epaper


http_request:


homeassistant_api:
  url: https://homeassistant.clantownsend.com/
  token: !secret home_assistant_token


calendar_events:
  id: events
  calendars:
    - calendar.mozilla_copy
    - calendar.personal
  duration: 24h
  on_update:
    - then:
        - component.update: epaper


weather_forecast:
  - id: weather_hourly
    entity_id: weather.openweathermap
    type: hourly
    update_interval: 10min
    on_update:
      - then:
          - component.update: epaper
  - id: weather_daily
    entity_id: weather.openweathermap
    type: daily
    update_interval: 30min
    on_update:
      - then:
          - component.update: epaper


flights:
  id: local_flights
  entity_id: sensor.flightradar24_current_in_area
  update_interval: 10s
  on_update:
    - then:
        - component.update: epaper


display:
  - id: !extend epaper
    update_interval: never
    full_update_every: 50
    lambda: |-
      dashboard::render_dashboard(it);
