esphome:
  name: display-office
  includes:
    - "includes/shared.h"
    - "display-office.h"
  on_boot:
    - then:
        - component.update: epaper


packages:
  - !include includes/base.yaml
  - !include includes/esp32c3.yaml
  - !include includes/waveshare.yaml


font:
  - file: "gfonts://Material+Symbols+Outlined"
    id: icons256
    size: 256
    glyphs:
      - "\U0000e63e"
      - "\U0000f063"
      - "\U0000e833"


api:
  on_client_connected:
    - component.update: epaper

  on_client_disconnected:
    - component.update: epaper


wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Display-Office Fallback Hotspot"
    password: "wwhbTrI9hT2A"

  on_connect:
    - component.update: epaper
  on_disconnect:
    - component.update: epaper


captive_portal:


time:
  - platform: sntp
    id: rtc
    timezone: Europe/London
    on_time:
      - seconds: 0
        then:
          - component.update: epaper
    on_time_sync:
      then:
        - component.update: epaper


text_sensor:
  - platform: homeassistant
    id: current_event_summary
    entity_id: sensor.current_event
    on_value:
      then:
        - component.update: epaper
  - platform: homeassistant
    id: current_event_start
    entity_id: sensor.current_event
    attribute: start
    on_value:
      then:
        - component.update: epaper
  - platform: homeassistant
    id: current_event_end
    entity_id: sensor.current_event
    attribute: end
    on_value:
      then:
        - component.update: epaper
  - platform: homeassistant
    id: next_event_summary
    entity_id: sensor.next_event
    on_value:
      then:
        - component.update: epaper
  - platform: homeassistant
    id: next_event_start
    entity_id: sensor.next_event
    attribute: start
    on_value:
      then:
        - component.update: epaper
  - platform: homeassistant
    id: next_event_end
    entity_id: sensor.next_event
    attribute: end
    on_value:
      then:
        - component.update: epaper


display:
  - id: !extend epaper
    update_interval: never
    full_update_every: 50
    lambda: |-
      dashboard::render_dashboard(it);
