esphome:
  name: display-office
  includes:
    - "includes/shared.h"
    - "display-office.h"
  on_boot:
    - then:
        - component.update: epaper


packages:
  - !include includes/base.yaml
  - !include includes/esp32c3.yaml
  - !include includes/waveshare.yaml


external_components:
  - source:
      type: local
      path: external_components


font:
  - file: "gfonts://Material+Symbols+Outlined"
    id: icons256
    size: 256
    glyphs:
      - "\U0000e63e"
      - "\U0000f063"


wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Display-Office Fallback Hotspot"
    password: "wwhbTrI9hT2A"

  on_connect:
    - component.update: epaper
    - component.update: events
  on_disconnect:
    - component.update: epaper


captive_portal:


time:
  - platform: homeassistant
    id: rtc
    timezone: Europe/London
    on_time:
      - seconds: 0
        then:
          - component.update: epaper
    on_time_sync:
      then:
        - component.update: epaper


http_request:


homeassistant_api:
  url: https://homeassistant.clantownsend.com/
  token: !secret home_assistant_token


calendar_events:
  id: events
  calendars:
    - calendar.mozilla_copy
    - calendar.personal
  duration: 24h
  on_update:
    - then:
        - component.update: epaper


display:
  - id: !extend epaper
    update_interval: never
    full_update_every: 50
    lambda: |-
      dashboard::render_dashboard(it);
