esphome:
  name: garage-motion
  platformio_options:
    platform: https://github.com/mnowak32/platform-espressif32.git#boards/seeed_xiao_esp32c6

esp32:
  board: seeed_xiao_esp32c6
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.2.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Enable logging
logger:
  baud_rate: 115200
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "MagnetIOT"
  password: ""

  manual_ip:
    static_ip: 10.10.96.1
    gateway: 10.10.96.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Motion Fallback Hotspot"
    password: "wwhbTrI9hT2A"

captive_portal:

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: false

binary_sensor:
  - platform: gpio
    device_class: motion
    name: "Motion"
    pin:
      number: GPIO17
      mode:
        input: true
        pulldown: true

sensor:
  - platform: htu31d
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
