[tools]
python = "3.11"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.setup]
run = "uv pip install -r requirements.txt"

[tasks.compile]
run = "esphome compile"

[tasks.run]
run = "esphome run"
