esphome:
  name: sensor-garage


packages:
  - !include includes/base.yaml
  - !include includes/esp32c6.yaml


api:
  on_client_connected:
    - output.turn_on: led

  on_client_disconnected:
    - if:
        condition:
          api.connected:
        then:
          - output.turn_off: led


wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Motion Fallback Hotspot"
    password: "wwhbTrI9hT2A"


captive_portal:


binary_sensor:
  - platform: gpio
    device_class: motion
    name: "Motion"
    pin:
      number: GPIO17
      mode:
        input: true
        pulldown: true


sensor:
  - platform: htu31d
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
