esphome:
  name: sensor-loft


packages:
  - !include includes/base.yaml
  - !include includes/esp32c6.yaml


api:
  on_client_connected:
    - output.turn_on: led

  on_client_disconnected:
    - if:
        condition:
          api.connected:
        then:
          - output.turn_off: led


wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Loft-Sensor Fallback Hotspot"
    password: "wwhbTrI9hT2A"


captive_portal:


sensor:
  - platform: htu21d
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    heater:
      name: "Heater"
